bs522_icons191
helloflask/bootstrap-flask pull request #257
Opened 2022-11-01 17:39 UTC by PanderMusubi

2022-11-02 15:10 UTC, greyli requested changes

2022-11-02 15:10 UTC, greyli commented on .github/workflows/build.yml
> +        python: ['3.6', '3.7', '3.8', '3.9', '3.10']
This change isn't in the scope of this PR, please submit the changes to build.yml/tox.in in a separate PR.

2022-11-02 15:11 UTC, greyli commented
Please update the title and comment to describe the PR.

2022-11-02 15:33 UTC, PanderMusubi commented
> Please update the title and comment to describe the PR.

Done in https://github.com/helloflask/bootstrap-flask/pull/258

2022-11-07 11:56 UTC, greyli commented
Please remove the change in setup.py, which is already included with #258.

2022-11-07 15:24 UTC, PanderMusubi commented
> Please remove the change in setup.py, which is already included in #258.
> 
> Also, please update the changelog.

done

2022-11-11 12:35 UTC, greyli commented
Please update the changelog.

2022-11-11 15:02 UTC, PanderMusubi commented
> Please update the changelog.

done

2022-11-13 03:08 UTC, greyli approved these changes

2022-11-13 03:08 UTC, merged

2022-11-13 03:08 UTC, greyli commented
Thanks!