render enum in table
helloflask/bootstrap-flask pull request #271
Opened 2023-02-21 10:05 UTC by PanderMusubi

2023-03-05 08:27 UTC, greyli commented
Please add some tests for this change and update the changelog.

2023-03-05 11:19 UTC, PanderMusubi commented
Tests are already in https://github.com/helloflask/bootstrap-flask/pull/271/commits/3e5507d1b9773231ee7af0dd5bcfc8ab668ae7ac#diff-5041814f41c9cf2e44c8ee9ec3f448747d7f32492b0d0586f4eda9b7f69a6b27

Update of changes is in https://github.com/helloflask/bootstrap-flask/pull/271/commits/b8f87c9150c7720b364dc5930a639d0ab9fdf837

2023-04-04 06:56 UTC, PanderMusubi commented
@greyli can you review this? Thanks.

2023-04-04 09:51 UTC, greyli requested changes

2023-04-04 09:51 UTC, greyli commented on CHANGES.rst
> +- Renden enums in tables by their labels.
```suggestion
- Render enums in tables by their labels.
```

2023-04-05 13:21 UTC, merged